--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  name: mongo-controller
spec: 
  replicas: 1
  selector: 
    app: mongo
  template: 
    metadata: 
      labels: 
        app: mongo
    spec: 
      containers: 
        - 
          env: 
            - 
              name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: 
                secretKeyRef: 
                  key: mongo-root-username
                  name: springapp-configmap
            - 
              name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: mongo-root-password
                  name: springapp-configmap
          image: mongo
          name: mongo
          ports: 
            - 
              containerPort: 27017
          volumeMounts: 
            - 
              mountPath: /data/db
              name: mongo-persistent-storage
      volumes: 
        - 
          hostPath: 
            path: /tmp/dbbackup
          name: mongo-persistent-storage

             

--- 
apiVersion: v1
kind: Service
metadata: 
  name: mongodb-service
spec: 
  ports: 
    - 
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector: 
    app: mongodb
